name: native_toolchain_meson
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  glob: ^2.1.2
  logging: ^1.3.0
  native_assets_cli: ^0.9.0
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
