name: native_toolchain_meson
description: Use Meson projects in Dart native assets build hooks.
version: 0.0.0

environment:
  sdk: ^3.5.4

dependencies:
  glob: ^2.1.2
  logging: ^1.3.0
  meta: ^1.16.0
  native_assets_cli: ^0.9.0
  path: ^1.9.1
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
