name: CI

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        sdk: [stable, dev]


    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
        if: ${{ matrix.os != 'macos' }}

      - run: pip3 install --break-system-packages meson==1.0.0

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .

      - name: Install native toolchains
        run: sudo apt-get update && sudo apt-get install clang-15 gcc-i686-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-riscv64-linux-gnu
        if: ${{ matrix.os == 'ubuntu' }}

      - run: dart test
